tunnel: 870732ff-8a9c-42f9-8e69-1e72fa28555f
credentials-file: C:\Users\zeNk0\.cloudflared\870732ff-8a9c-42f9-8e69-1e72fa28555f.json

ingress:
  - hostname: chatbot.zgamersa.com
    service: http://localhost:7847
  - service: http_status:404
